//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalks.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public int WalkID { get; set; }
        public string AuthorID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    
        public virtual DogWalk DogWalk { get; set; }
    }
}
