//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalks.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogWalk
    {
        public DogWalk()
        {
            this.Comments = new HashSet<Comment>();
            this.Ratings = new HashSet<Rating>();
            this.Features = new HashSet<Feature>();
            this.Pictures = new HashSet<Picture>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int WalkID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string Location { get; set; }
        public string Postcode { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public int LengthID { get; set; }
        public string WebsiteUrl { get; set; }
        public Nullable<int> AuthorID { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Feature> Features { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual Length Length { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
