//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalks.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WalkContext : DbContext
    {
        public WalkContext()
            : base("name=WalkContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<DogWalk> DogWalks { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<PostCodesUK> PostCodesUKs { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Length> Lengths { get; set; }
    }
}
